name: Deploy SpringBoot to AWS EC2 (minimal)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Spring Boot (skip tests)
        run: ./mvnw -B -DskipTests package

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Upload JAR (scp)
        run: |
          JAR_FILE=$(ls -t target/*.jar | head -n 1)
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p ~/app-delicia/logs"
          scp "$JAR_FILE" ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/app-delicia/app.jar

      - name: Restart app (nohup + PID file)
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd ~/app-delicia

            # Instalar Java si no existe (requiere sudo)
            if ! command -v java >/dev/null 2>&1; then
              sudo apt-get update && sudo apt-get install -y openjdk-17-jre
            fi

            # Parar si está corriendo
            if [ -f app.pid ] && kill -0 $(cat app.pid) 2>/dev/null; then
              echo "Stopping previous process..."
              kill $(cat app.pid) || true
              sleep 2
              if kill -0 $(cat app.pid) 2>/dev/null; then
                echo "Force kill..."
                kill -9 $(cat app.pid) || true
              fi
              rm -f app.pid
            fi

            # Arrancar en segundo plano con logs
            nohup java -jar ./app.jar > ./logs/app.out 2>&1 &
            echo $! > app.pid
            echo "Started with PID $(cat app.pid)"
          EOF
